# executable files for this directory
OBJECTS = ex11_03_04.exe ex11_07.exe ex11_08.exe \

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../../GNU_makefile_template

LOCFLAGS =

